#!/bin/bash

source ./modules/ask.sh
source ./modules/download.sh
source ./modules/note.sh

### COMMENTED INSTRUCTIONS WILL BE UNCOMMENTED LATER ON.

clear

### Install script for my Arch system.

# timedatectl set-ntp true

### Choose where to install /boot, root and swap
notecommands+=('lsblk -dp -o NAME,SIZE | column -t' 'lsblk -p -o NAME,SIZE,PARTUUID | column -t')

echo "Welcome to the install script!"

echo "On your right, a funny thing should tell you
everything you need to know about your hard drives."

drawnote

askopt "What kinda partitioning config do you want?"\
    "just root, on one disk"\
    "root and /home on different partitions, still one disk"\
    "root on one disk, /home on other disk"\
    "option \"do it yourself fucker\" (will launch you in fdisk)"

echo "Main script: Answer is $?"

notecommands=("${notecommands[@]:1}")

drawnote

askyn "Do you want swap?"

echo "Main script: Answer is $?"

### Choose where to install /home
# lsblk -d -o NAME,SIZE
